In [1]:
import tensorflow as tf
from transformers import BertTokenizer
import pandas as pd

In [16]:
import tensorflow as tf
from transformers import TFAutoModelForSequenceClassification
from transformers import BertTokenizer
from transformers import AutoModelForSequenceClassification


# Muat model dari file .h5
model = TFAutoModelForSequenceClassification.from_pretrained("modelbert")
# Load the tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')



Some layers from the model checkpoint at modelbert were not used when initializing TFBertForSequenceClassification: ['dropout_75']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at modelbert.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.
c:\Users\acer\anaconda3\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarn

In [32]:
import numpy as np

def predict(new_texts):
    # Tokenize the new texts
    new_encodings = tokenizer(new_texts, padding=True, truncation=True, max_length=512, return_tensors='tf')

    # Make predictions
    predictions = model(new_encodings)

    # Get probabilities using softmax
    probabilities = tf.nn.softmax(predictions.logits, axis=-1).numpy()

    # Get predicted labels
    predicted_labels = np.argmax(probabilities, axis=1)
    
    # Print predicted labels and their probabilities
    for i, text in enumerate(new_texts):
        print(f"Text: {text}")
        print(f"Predicted Label: {predicted_labels[i]}")
        print(f"Probabilities: {probabilities[i]}")
        print("-" * 50)

    return predicted_labels, probabilities

In [33]:
new_texts = [
    "Today I was alone eating in cafetaria. it such a piece moment for myself. But i dont know what to feel. it feel strange yet thrilling being alone in such crowded place"
]

predict(new_texts)

Text: Today I was alone eating in cafetaria. it such a piece moment for myself. But i dont know what to feel. it feel strange yet thrilling being alone in such crowded place
Predicted Label: 2
Probabilities: [0.01352774 0.07948735 0.90698487]
--------------------------------------------------


(array([2], dtype=int64),
 array([[0.01352774, 0.07948735, 0.90698487]], dtype=float32))

In [40]:
coba2 = [
    " conversation ive recently asked worried would regret continuing university career exchange humble job grocery store inwardly anxious person suddenly stuck fact kept awake night choice come realize note transition previous anxious self accepting confident person realized chosen continue schooling would always regretted opportunity different would felt missed opportunity contrary decision would produced see short year existence subconsciously come understand something nature personal experience view life always wonder possibility unknown always view definite course action le freedom possibility word always chase matter path select long opportunity could benefit could gained done different enter decision understanding every choice extinguish possibility offered choice framework evaluation change drastically instead deciding based best remove regret suffering see choice always produce regret must arise new reason new framework affect decision new method discernment hope hope decision best pursuing college would meant staying parent protection duration study attempt find job brother chose path witnessed restrain ability strike assume total responsibility life remains constrained goal set parent attainment life built upon effort parent least part gave ability go college forfeit joy understanding produced life instead choose hope remember noble struggle see effort struggle hard choice produced good life regret  produced choice stand testament ability take heart aspiration eye seen yield fear truly empowering sight fear master dove lake fear surrounding choice settle emerged unscathed bolstered experience look regret great sea whose tempest seek dissuade fearful fisherman reaching still water bounty caught allow take great responsibility great  failure therein achieve feeling accomplishment suffering fear emotion driving  say behemoth feeding thoughtfulness think life thoroughly uncover disheartening underbelly objective look nature existence produce image suffering suffering lying wait behind every misstep anxious people see possibility negativity le likely disregard genetically inclined focus negative mean safety person think environment might dangerous best get survives unlike person disregard possibility danger becomes lion dinner evolution tailored u anxious mindset still alive gene awoken experience situation disregarded possibility danger ended getting hurt emotionally physically left wondering perfect environment mindset establish something childhood hurt u much developed way assure never happen gave  power control u exchange safety hard regain control especially event traumatic done  told show helpless victim chose take path would filled  give damn would able deter desire limited   lost shunned back dormant home"
]

predict(coba2)

Text:  conversation ive recently asked worried would regret continuing university career exchange humble job grocery store inwardly anxious person suddenly stuck fact kept awake night choice come realize note transition previous anxious self accepting confident person realized chosen continue schooling would always regretted opportunity different would felt missed opportunity contrary decision would produced see short year existence subconsciously come understand something nature personal experience view life always wonder possibility unknown always view definite course action le freedom possibility word always chase matter path select long opportunity could benefit could gained done different enter decision understanding every choice extinguish possibility offered choice framework evaluation change drastically instead deciding based best remove regret suffering see choice always produce regret must arise new reason new framework affect decision new method discernment hope hope decisio

(array([0], dtype=int64),
 array([[9.9842608e-01, 9.7146229e-04, 6.0244434e-04]], dtype=float32))

In [45]:
aaa = ["The quiet of the night offers no solace, as my mind races with a million scenarios, each more catastrophic than the last, leaving me trapped in a cycle of worry and restlessness.."]
predict(aaa)

Text: The quiet of the night offers no solace, as my mind races with a million scenarios, each more catastrophic than the last, leaving me trapped in a cycle of worry and restlessness..
Predicted Label: 0
Probabilities: [0.876691   0.0981718  0.02513717]
--------------------------------------------------


(array([0], dtype=int64),
 array([[0.876691  , 0.0981718 , 0.02513717]], dtype=float32))